name: goLangPOC-test
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests: 
    name: run-poc-test

    runs-on: windows-latest  #ubuntu-latest

    steps: 
      - name: CheckOut
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 18.14.0
      - uses: microsoft/playwright-github-action@v1
           
      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Getting User Credentials secrets
        env: 
           UNAME:   ${{vars.USERNAME}}
           PASSORD:   ${{vars.PASSWORD}}

        run: | 
            echo "$UNAME"
            echo "$PASSORD"

      - name: Run tests
        run: $env:USERNAME=${{vars.USERNAME}};$env:PASSWORD=${{vars.PASSWORD}};npx playwright test goLangPoc --workers 1 --project chromium --heade
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30