name: Evatic-Test-Suite
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests: 
    name: run-vo-test

    runs-on: windows-latest  #ubuntu-latest

    steps: 
      - name: CheckOut
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 18.14.0
      - uses: microsoft/playwright-github-action@v1
           
      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Getting User Credentials secrets
        env: 
           UNAME:   ${{secrets.UN}}
           PASSORD:   ${{secrets.PW}}

        run: | 
            echo "$UNAME"
            echo "$PASSORD"

      - name: Run tests
        run: $env:USERNAME='${{secrets.UN}}';$env:PASSWORD='${{secrets.PW}}';npx playwright test --workers 1 --project="chromium" --headed

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30