name: Default env vairables
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  default-env-variables: 
    runs-on: ubuntu-latest  #windows-latest
    steps: 
      - name: Testing Secrets                   
        env: 
            DEVOPS:   ${{secrets.SECRETS_TOKEN}}
        run: | 
            echo "$DEVOPS"
            