name: Default env vairables
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  default-env-variables: 
    runs-on: ubuntu-latest  #windows-latest
    steps: 
      - name: Testing Secrets
        run: | 
             echo "$DEVOPS"
             if[ "$DEVOPS" == "Test" ]
             then
                echo "Got your secret"
              fi
        env: 
            DEVOPS:   ${{secrets.SECRETS_TOKEN}}
            